language: generic
os: linux
dist: trusty
branches:
    only:
      - develop
      - master
addons:
  apt:
    packages:
      - gettext
      - libcurl4-openssl-dev
      - libicu-dev
      - libssl-dev
      - libunwind8
      - zlib1g
      - curl
script: ./condo.sh -- /t:ci
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/083d3b3e6c59d2c8838d
    on_success: change
    on_failure: always
    on_start: never
